#!/bin/bash
# Download Raspbian Image, remove first-boot stuff, add repos and install packages.
#
# Open interactive Shell in chroot or write result to SD Card
#
# License: GNU General Public License, see http://www.gnu.org/copyleft/gpl.html for full text
#
# The following variables and arrays customize the behavior. To change them simply create a configuration
# file `pirateship-image-creator.config` which overrides them.
#
# Add at least the following lines to override the internal configuration:
# INSTALL_PACKAGES=()
# ADD_REPOS=()
# ADD_REPO_KEYS=()

# Raspbian
RASPBIAN_URL=http://people.sugarlabs.org/ignacio/2017-04-10-raspbian-jessie.zip
RASPBIAN_SHA1=6d7b11bb3d64524203edf6c80c499456fb5fef53
#RASPBIAN_URL=http://downloads.raspberrypi.org/raspbian/images/raspbian-2017-01-10/2017-01-11-raspbian-jessie.zip
#RASPBIAN_SHA1=f987935e3e99366a6f1bf0d60a7a83fe3edb013c

############ End of User Cusomization

source lib.sh

missing_deps=()
for prog in kpartx wget gpg parted qemu-arm-static ; do
    if ! type $prog &>/dev/null ; then
        missing_deps+=( $prog )
    fi
done
if (( ${#missing_deps[@]} > 0 )) ; then
    die "Missing required programs: ${missing_deps[*]}
    On Debian/Ubuntu try 'sudo apt-get install kpartx qemu-user-static parted'"
fi

function _umount {
    for dir in "$@" ; do
        if grep -q "$dir" /proc/self/mounts ; then
            if ! umount -f "$dir" ; then
                die "Could not umount $dir, check running procs:$NL$(lsof 2>/dev/null | grep $(readlink -f $dir))"
            fi
        fi
    done
}

function _get_image {
    echo "Fetching $RASPBIAN_URL "
    mkdir -p images
    wget --continue --progress=dot:giga --directory-prefix images $RASPBIAN_URL || die "Download of $RASPBIAN_URL failed"
    echo -n "Checksum of "
    sha1sum --strict --check - <<<"$RASPBIAN_SHA1 *$IMAGE_ZIP" || die "Download checksum validation failed, please check http://www.raspberrypi.org/downloads"
    unzip $IMAGE_ZIP -d images || die "Could not unzip $IMAGE_ZIP"
}

function _disable_daemons {
    # Prevent services from being started inside the chroot.
    POLICY_RC_D=mnt/img_root/usr/sbin/policy-rc.d
    echo "#!/bin/sh" >> $POLICY_RC_D
    echo "exit 101"  >> $POLICY_RC_D
    chmod +x $POLICY_RC_D
}

function _enable_daemons {
    POLICY_RC_D=mnt/img_root/usr/sbin/policy-rc.d
    rm -f $POLICY_RC_D
}

function _disable_ld_preload {
    cfg=mnt/img_root/etc/ld.so.preload

    if grep -q '^[^#]' $cfg; then
        sed -i -e 's/^/#/' $cfg || die "Could not disable ld.so.preload"
    fi
}

function _enable_ld_preload {
    cfg=mnt/img_root/etc/ld.so.preload

    if grep -q '^#' $cfg; then
        sed -i -e 's/^#//' $cfg || die "Could not enable ld.so.preload"
    fi
}

function _open_image {
    echo "Loop-back mounting" images/*.img
    kpartx="$(kpartx -sav images/*.img)" || die "Could not setup loop-back access to $RASPBIAN_ARCHIVE_FILE:$NL$kpartx"
    read -d '' img_boot_dev img_root_dev <<<$(grep -o 'loop.p.' <<<"$kpartx")
    test "$img_boot_dev" -a "$img_root_dev" || die "Could not extract boot and root loop device from kpartx output:$NL$kpartx"
    img_boot_dev=/dev/mapper/$img_boot_dev
    img_root_dev=/dev/mapper/$img_root_dev
    mkdir -p mnt/img_root
    mount -t ext4 $img_root_dev mnt/img_root || die "Could not mount $img_root_dev mnt/img_root"
    mkdir -p mnt/img_root/boot || die "Could not mkdir mnt/img_root/boot"
    mount -t vfat $img_boot_dev mnt/img_root/boot || die "Could not mount $img_boot_dev mnt/img_root/boot"
    echo "Raspbian Image Details:"
    df -h mnt/img_root/boot mnt/img_root | sed -e "s#$(pwd)/##"
}

function _close_image {
    _umount mnt/img_root/var/cache/apt/archives \
        mnt/img_root/{proc,sys,run,dev/pts} \
        mnt/sd_root/bo?t mnt/img_root/boot \
        mnt/sd_ro?t mnt/img_root
    kpartx -d images/*.img >/dev/null
}

function _prepare_chroot {
    _disable_ld_preload

    cp -a "$(type -p qemu-arm-static)" mnt/img_root/usr/bin/ || die "Could not copy qemu-arm-static"
    _chroot date &>/dev/null || die "Could not chroot date"

    mount -t devpts devpts -o noexec,nosuid,gid=5,mode=620 mnt/img_root/dev/pts || die "Could not mount /dev/pts"
    mount -t proc proc mnt/img_root/proc || die "Could not mount /proc"
    mount -t tmpfs -o mode=1777 none mnt/img_root/run || "Could not mount /run"

    mkdir -p apt_cache
    mount --bind apt_cache mnt/img_root/var/cache/apt/archives
}

function _cleanup_chroot {
    _umount mnt/img_root/var/cache/apt/archives \
        mnt/img_root/{proc,sys,run,dev/pts}
    _enable_daemons
    _enable_ld_preload
}

function _modify_image {
    echo "Modifying Image"

    _prepare_chroot
    _disable_daemons

    run-parts --exit-on-error -v --regex '[a-zA-Z.-_]*' scripts.d ||\
        die "Image modification scripts failed"

    _enable_daemons
    _cleanup_chroot
}

function _usage {
    echo "
Usage: $0 <--chroot|--noninteractive>

Download Raspbian Image, remove first-boot stuff, add repos and install packages.

Open interactive Shell in chroot or write result to SD Card

License: GNU General Public License, see http://www.gnu.org/copyleft/gpl.html for full text
"
}

export LANG="C" LANGUAGE="C" LC_ALL="C.UTF-8"
shopt -s nullglob

if [[ $# -eq 0 || "$*" == *-h* ]] ; then
    _usage
    exit 1
fi

if [[ "$USER" != root && $(id -u) != "0" ]] ; then
    # restart as root
    echo "Switching over to run as root"
    exec sudo "$(readlink -f "$0")" "$@"
    echo "Need sudo permission to run as root!"
    exit 1
fi

if grep -wq $(readlink -f mnt) /proc/self/mounts; then
    die "mnt/ is already mounted!"
fi

rm -Rf --one-file-system mnt temp
function exittrap {
    set +u +e
    _close_image
    echo "Script execution time: $SECONDS seconds"
}
trap exittrap 0
trap exittrap ERR

IMAGE_ZIP=images/${RASPBIAN_URL##*/}
IMAGE=${IMAGE_ZIP%.zip}.img

if [ ! -e "$IMAGE" ]; then
    _get_image
fi

_open_image
_modify_image

if [[ "$1" == "--chroot" ]] ; then
    echo "Starting interactive Shell in image chroot"
    _prepare_chroot
    chroot mnt/img_root bash -i
    _cleanup_chroot
    exit 0
elif [[ "$1" == "--noninteractive" ]] ; then
    :
else
    die "Usage error. Try $0 --help"
fi


# vim:autoindent:tabstop=2:shiftwidth=2:expandtab:softtabstop=2:
