#!/bin/bash

hostname='ole'
hotspotname='ole'
moodleversion='3.4'
moodoleport='8080'
bellport='5984'

pirateship rename $hostname
pirateship expandfs

# moodole
wget -O /home/pi/moodole.yml https://raw.githubusercontent.com/ole-vi/moodole/master/$moodleversion/arm/docker-compose-ready.yml
sed -i "/ports:/ { n; s/80:80/$moodoleport:80/; }" /home/pi/moodole.yml
docker-compose -f /home/pi/moodole.yml -p moodole up -d --build

# BellApps
# create couchdb docker container
docker run -d -p $bellport:5984 --name bell -v /srv/data/bell:/usr/local/var/lib/couchdb -v /srv/log/bell:/usr/local/var/log/couchdb dogi/rpi-couchdb

# redirect to bell
mkdir -p /root/ole
echo '#!/usr/bin/env node' > /root/ole/server.js
echo '' >> /root/ole/server.js
echo "var express = require('express')" >> /root/ole/server.js
echo 'var PortJack = express()' >> /root/ole/server.js
echo 'PortJack.get(/^(.+)$/, function(req, res) {' >> /root/ole/server.js
echo 'var options = {' >> /root/ole/server.js
echo '"'$hostname'.local": "http://'$hostname'.local:'$bellport'/apps/_design/bell/MyApp/index.html",' >> /root/ole/server.js
echo '"192.168.2.1": "http://192.168.2.1:'$bellport'/apps/_design/bell/MyApp/index.html",' >> /root/ole/server.js
echo '"192.168.0.99": "http://192.168.0.99:'$bellport'/apps/_design/bell/MyApp/index.html",' >> /root/ole/server.js
echo '"192.168.1.99": "http://192.168.4.99:'$bellport'/apps/_design/bell/MyApp/index.html"' >> /root/ole/server.js
echo '}' >> /root/ole/server.js
echo 'if (options.hasOwnProperty(req.hostname)) {' >> /root/ole/server.js
echo "res.setHeader('Location', options[req.hostname])" >> /root/ole/server.js
echo '}' >> /root/ole/server.js
echo 'else {' >> /root/ole/server.js
echo "res.setHeader('Location', 'http://ole.org')" >> /root/ole/server.js
echo '}' >> /root/ole/server.js
echo 'res.statusCode = 302' >> /root/ole/server.js
echo 'res.end()' >> /root/ole/server.js
echo '})' >> /root/ole/server.js
echo 'PortJack.listen(80)' >> /root/ole/server.js
chmod +x /root/ole/server.js
cd /root/ole
npm install express

# start moodole and BellApps on boot
cat <<EOF > /boot/autorun
#!/bin/sh

sleep 2
rm -rf /home/pi/apache2
mkdir -p /home/pi/apache2
docker-compose -f /home/pi/moodole.yml -p moodole start

sleep 10
docker start bell
node /root/ole/server.js
EOF

pirateship hotspot $hotspotname
