#!/bin/bash

hostname='ole'
hotspotname='treehouse'
moodleversion='3.4'
moodoleport='8080'
bellport='5984'

# real time clock: rasclock or ds3231
rtc='rasclock'
# rtc='ds3231'

treehouses rename $hostname
treehouses expandfs

# moodole
wget -O /home/pi/moodole.yml https://raw.githubusercontent.com/ole-vi/moodole/master/$moodleversion/arm/docker-compose-ready.yml
sed -i "/ports:/ { n; s/80:80/$moodoleport:80/; }" /home/pi/moodole.yml
docker-compose -f /home/pi/moodole.yml -p moodole up -d --build

# BellApps
# create couchdb docker container
docker run -d -p $bellport:5984 --name bell -v /srv/bell/data:/usr/local/var/lib/couchdb -v /srv/bell/log:/usr/local/var/log/couchdb treehouses/couchdb:1.7.1

# check if docker is running
while ! curl -X GET http://127.0.0.1:$bellport/_all_dbs ; do
  sleep 1
done

curl -d @/srv/bell/conf/ConfigurationsDoc-Community.txt -H "Content-Type: application/json" -X POST http://127.0.0.1:$bellport/configurations

# redirect to bell
mkdir -p /root/ole
{
  echo '#!/usr/bin/env node'
  echo ''
  echo "var express = require('express')"
  echo 'var PortJack = express()'
  echo 'PortJack.get(/^(.+)$/, function(req, res) {'
  echo 'var options = {'
  echo '"'$hostname'.local": "http://'$hostname'.local:'$bellport'/apps/_design/bell/MyApp/index.html",'
  echo '"192.168.2.1": "http://192.168.2.1:'$bellport'/apps/_design/bell/MyApp/index.html",'
  echo '"192.168.0.99": "http://192.168.0.99:'$bellport'/apps/_design/bell/MyApp/index.html",'
  echo '"192.168.1.99": "http://192.168.4.99:'$bellport'/apps/_design/bell/MyApp/index.html"'
  echo '}'
  echo 'if (options.hasOwnProperty(req.hostname)) {'
  echo "res.setHeader('Location', options[req.hostname])"
  echo '}'
  echo 'else {'
  echo "res.setHeader('Location', 'http://ole.org')"
  echo '}'
  echo 'res.statusCode = 302'
  echo 'res.end()'
  echo '})'
  echo 'PortJack.listen(80)' 
} > /root/ole/server.js
chmod +x /root/ole/server.js
cd /root/ole || exit 1
npm install express

# real time clock
treehouses rtc on "$rtc"

# second autorunonce
mv /boot/autoranonce* /boot/autoranonce.first
sync
cat <<EOF > /boot/autorunonce
#!/bin/sh
sleep 10
while ! curl -X GET https://google.com ; do
  sleep 1
done
sudo treehouses ntp local
# write '/boot/autorun', start moodole and BellApps on boot
echo '#!/bin/sh' > /boot/autorun
echo '' >> /boot/autorun
echo 'sleep 2' >> /boot/autorun
echo 'docker-compose -f /home/pi/moodole.yml -p moodole start' >> /boot/autorun
echo '' >> /boot/autorun
echo 'sleep 10' >> /boot/autorun
echo 'docker start bell' >> /boot/autorun
echo 'node /root/ole/server.js' >> /boot/autorun
sync;sync;sync;reboot
EOF

treehouses hotspot $hotspotname

sync
sync
sync

reboot
