#!/bin/bash

hostname='ole'
hotspotname='treehouse'
port='5984'

pirateship rename $hostname
pirateship expandfs

# create couchdb docker container
docker run -d -p $port:5984 --name bell -v /srv/data/bell:/usr/local/var/lib/couchdb -v /srv/log/bell:/usr/local/var/log/couchdb dogi/rpi-couchdb

# write '/boot/autrun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker start bell'
} > /boot/autorun.sh

# redirect to bell
mkdir -p /root/ole
{
  echo '#!/usr/bin/env node'
  echo ''
  echo "var express = require('express')"
  echo 'var PortJack = express()'
  echo 'PortJack.get(/^(.+)$/, function(req, res) {'
  echo 'var options = {'
  echo '"'$hostname'.local": "http://'$hostname'.local:'$port'/apps/_design/bell/MyApp/index.html",'
  echo '"192.168.2.1": "http://192.168.2.1:'$port'/apps/_design/bell/MyApp/index.html",'
  echo '"192.168.0.99": "http://192.168.0.99:'$port'/apps/_design/bell/MyApp/index.html",'
  echo '"192.168.1.99": "http://192.168.4.99:'$port'/apps/_design/bell/MyApp/index.html"'
  echo '}'
  echo 'if (options.hasOwnProperty(req.hostname)) {'
  echo "res.setHeader('Location', options[req.hostname])"
  echo '}'
  echo 'else {'
  echo "res.setHeader('Location', 'http://ole.org')"
  echo '}'
  echo 'res.statusCode = 302'
  echo 'res.end()'
  echo '})'
  echo 'PortJack.listen(80)'
} > /root/ole/server.js
chmod +x /root/ole/server.js
cd /root/ole || exit 1
npm install express

# add to '/boot/autorun.sh'
echo '' >> /boot/autorun.sh
echo 'node /root/ole/server.js' >> /boot/autorun.sh

pirateship hotspot $hotspotname

sync
sync
sync

reboot
