#!/bin/bash

hostname='ole'
hotspotname='treehouse'
moodleversion='3.4'

pirateship rename $hostname
pirateship expandfs

wget -O /home/pi/moodole.yml https://raw.githubusercontent.com/treehouses/moodole/master/$moodleversion/arm/docker-compose-ready.yml
docker-compose -f /home/pi/moodole.yml -p moodole up -d --build

# write '/boot/autorun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker-compose -f /home/pi/moodole.yml -p moodole start'
} > /boot/autorun

pirateship hotspot $hotspotname

sync
sync
sync

reboot
