#!/bin/bash

{
  echo 'services:'
  echo '  netdata:'
  echo '      image: firehol/netdata:armv7hf'
  echo '      ports:'
  echo '          - "4949:19999"'
  echo '          - "19999:19999"'
  echo '      volumes:'
  echo '          - /proc:/host/proc'
  echo '          - /sys:/host/sys'
  echo '      cap_add:'
  echo '          - SYS_PTRACE'
  echo 'version: "2"'
} > /root/netdata.yml

{
  echo "#!/bin/sh"
  echo
  echo "sleep 1"
  echo "docker-compose -f /root/netdata.yml -p netdata up -d"
} > /boot/autorun

sync; sync; sync
/boot/autorun
