#!/bin/bash

hostname='ole'
hotspotname='treehouse'

treehouses rename $hostname
treehouses expandfs

# download Planet
cd /root || exit 1
git clone https://github.com/ole-vi/planet.git
cd planet/docker || exit 1
docker-compose -f rpi-planet.yml -p rpi-planet up -d --build

# write '/boot/autorun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker-compose -f /root/planet/docker/rpi-planet.yml -p rpi-planet start'
} > /boot/autorun

treehouses hotspot $hotspotname
