#!/bin/bash

hostname='ole'
hotspotname='treehouse'

treehouses rename $hostname
treehouses expandfs

# download Planet
cd /root || exit 1
wget https://raw.githubusercontent.com/open-learning-exchange/planet/master/docker/planet.yml
docker-compose -f planet.yml -p planet up -d --build

# write '/boot/autorun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker-compose -f /root/planet.yml -p planet start'
} > /boot/autorun

treehouses hotspot $hotspotname
