#!/bin/bash

hostname='ole'
hotspotname='treehouse'

# real time clock: rasclock or ds3231
rtc='rasclock'
# rtc='ds3231'

# real time clock
cd /boot/overlays || exit 1
echo >> /boot/config.txt

if [ "$rtc" = "rasclock" ]; then
  echo 'dtoverlay=i2c-rtc,pcf2127' >> /boot/config.txt
elif [ "$rtc" = "ds3231" ]; then
  echo 'dtoverlay=i2c-rtc,ds3231' >> /boot/config.txt
fi

cp /lib/udev/hwclock-set /lib/udev/hwclock-set.old
sed -e '/run\/systemd\/system/,+2 s/^#*/#/' -i /lib/udev/hwclock-set
sed -e '/--systz/ s/^#*/#/' -i /lib/udev/hwclock-set

# disable fake-hwclock
sudo apt-get -y remove fake-hwclock
sudo update-rc.d -f fake-hwclock remove

treehouses rename $hostname
treehouses expandfs
treehouses bluetooth on
#treehouses wifi <wifiname> [password]

# download Planet
cd /root || exit 1
wget https://raw.githubusercontent.com/open-learning-exchange/planet/master/docker/planet.yml
wget https://raw.githubusercontent.com/open-learning-exchange/planet/master/docker/install.yml

sync; sync; sync

docker-compose -f planet.yml -f install.yml -p planet pull
docker-compose -f planet.yml -f install.yml -p planet up -d
docker tag treehouses/planet:db-init treehouses/planet:db-init-local
docker tag treehouses/planet:latest treehouses/planet:local

sync; sync; sync

docker-compose -f planet.yml -p planet up -d

# second autorunonce
mv /boot/autoranonce* /boot/autoranonce.first
sync

{
  echo '#!/bin/sh'
  echo "sleep 10"
  echo
  echo "while ! curl -X GET https://google.com ; do"
  echo "  sleep 1"
  echo "done"
  echo
  echo "sudo service ntp restart"
  echo "sudo date > /boot/time"
  echo "sudo hwclock -w"
  echo "sudo hwclock -r >> /boot/time"
  echo "sudo hwclock -s"
  echo "sudo date >> /boot/time"
  echo
  echo "{"
  echo "  echo \"server 127.127.1.0\""
  echo "  echo \"fudge 127.127.1.0 stratum 10\""
  echo "  echo \"restrict 192.168.0.0 mask 255.255.0.0 nomodify notrap\""
  echo "} >> /etc/ntp.conf"
  echo
  # write '/boot/autorun', start moodole and BellApps on boot
  echo "{"
  echo "  echo \"@/bin/sh\""
  echo "  echo \"sleep 1\""
  echo "  echo \"docker-compose -f /root/planet.yml -p planet up -d\""
  echo "} >> /boot/autorun"
  echo "sed -i s/\@/#\!/g /boot/autorun"
  echo "sync;sync;sync; reboot"
} > /boot/autorunonce

treehouses hotspot $hotspotname
