title: "treehouses.io"
description: "hacker treehouses"
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://treehouses.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  treehouses
include: ['_docs']

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

