name: indexer

on:
  workflow_dispatch:

jobs:
  indexer:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          sudo apt-get update  
          sudo apt install s3fs
      - name: mount
        run: |
          echo "${{ secrets.AWSACCESSKEYID }}:${{ secrets.AWSACCESSKEYSECRET }}" > .passwd-s3fs
          chmod 600 .passwd-s3fs
          sudo rm -rf /var/www/html
          sudo mkdir -p /var/www/html
          sudo chmod 666 /var/www/html
          sudo s3fs treehouses /var/www/html -o passwd_file=./.passwd-s3fs -o allow_other
      - name: apache index
        run: |
          sudo mv /var/www/html/index.html index.html.old
          sudo sync
          sudo systemctl start apache2
          sudo curl http://localhost -o index.html
          sudo mv index.html.old /var/www/html/.
          sudo sync
          sudo mv ./index.html /var/www/html
          sudo rm /var/www/html/index.html.old
      - name: new index.html
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWSDISTRIBUTIONID }}
          PATHS: '/index.html'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSACCESSKEYSECRET }}
